implemented dao and service layers for Order entity
matviichuk92/cimena pull request #6
Opened 2020-10-12 07:46 UTC by matviichuk92

2020-10-12 08:07 UTC, andromash reviewed
Good job!

2020-10-12 08:07 UTC, andromash commented on src/main/java/com/cinema/dao/OrderDao.java
> +    List<Order> getOrderHistory(User user);
I suppose in this case we better use a more certain name of the method, getOrdersOfUser or getUsersOrders, etc.

2020-10-12 08:07 UTC, andromash commented on src/main/java/com/cinema/service/impl/OrderServiceImpl.java
> +        shoppingCartDao.update(shoppingCartDao.getByUser(user));
What are you updating here? Also, we need to clear the bucket (if that's what you wanted to do) via method from ShoppingCartService, and method clear should call this update

2020-10-12 08:18 UTC, matviichuk92 commented on src/main/java/com/cinema/service/impl/OrderServiceImpl.java
> +        shoppingCartDao.update(shoppingCartDao.getByUser(user));
абсолютно логічно, в мене щось уява розігралась :D

2020-10-12 20:41 UTC, KseniiaMakarova requested changes

2020-10-12 20:41 UTC, KseniiaMakarova commented on src/main/java/com/cinema/Application.java
> +    static final OrderService orderService
let's add access modifiers to these fields

2020-10-12 20:41 UTC, KseniiaMakarova commented on src/main/java/com/cinema/Application.java
>          shoppingCartService.addSession(session,roma);
let's register() users instead of calling `userService.add()` and then `shoppingCartService.registerNewShoppingCart()`

2020-10-12 20:41 UTC, KseniiaMakarova commented on src/main/java/com/cinema/dao/impl/OrderDaoImpl.java
> +            return session.createQuery(query).getResultList();
let's return only distinct values here

2020-10-13 08:25 UTC, KseniiaMakarova approved these changes

2020-10-15 11:32 UTC, merged